version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.20.0
    steps:
      - checkout
      - run:
          name: Build Go binary
          command: go build -o gin-sql-admin
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t gin-sql-admin:latest .
            docker login -u jerrt2003 -p uLAP8BDz3eRmy7y
            docker push jerrt2003/gin-sql-admin:latest